### ISSUE TITLE
Add autofix command

### ISSUE THREAD

**Issue by sQVe** [bmatcuk/coc-stylelintplus#16]
Hey 👋🏼,

This plugin is working nicely but I'm missing a command to run the `fix` manually like `coc-eslint` and `coc-stylelint` has. `coc-eslint` uses `eslint.executeAutofix` for example.

Would it be possible to add this feature? 🙏🏼

**Comment by bmatcuk** [comment]
Thanks, @sQVe! Support was already there for it, and it would appear in the quick fix list, but it wasn't exposed as a command. I just cut v1.4.0 which exposes it as a command as well so you can do `:CocCommand stylelintplus.applyAutoFixes` =)

**Comment by sQVe** [comment]
@bmatcuk That's awesome. Cheers for the quick fix! 🍻
