### ISSUE TITLE
Support for ccs-in-js

### ISSUE THREAD

**Issue by fffed** [bmatcuk/coc-stylelintplus#5]
Could you please add support for js{x}/ts{x} files so it starts working with css-in-js ala styled-components?
I do not sure if it all correct but I've created a pull request: https://github.com/bmatcuk/coc-stylelintplus/pull/6

**Comment by bmatcuk** [comment]
Closed by #6

**Comment by bmatcuk** [comment]
Hey @fffed, I've had to make css-in-js an optional feature, disabled by default, because it was causing some issues (see issue #7). If you upgrade to v1.2.0, you can enable it in your coc-settings.json by setting `stylelintplus.cssInJs` to true.
