### ISSUE TITLE
Cannot install via `:CocInstall`

### ISSUE THREAD

**Issue by crusoexia** [bmatcuk/coc-stylelintplus#9]
Install with exit code 1:

![Screen Shot 2020-09-15 at 1 34 23 PM](https://user-images.githubusercontent.com/5928754/93169780-71674f00-f758-11ea-83a5-5040dd2eb695.png)

Seems like it is using a wrong stylelint-lsp version.

**Comment by bmatcuk** [comment]
Hmm, something strange is happening... v1.0.6 of stylelint-lsp exists and is available on npm - I'm the author of that package as well. Do you have any sort of npm proxying setup, or some other non-standard environment?

**Comment by crusoexia** [comment]
I switched to yarn repository and tried again, it succeed. It's an issue of cnpm.
